# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Identity(Model):
    """Identity for the resource.

    :param type: The identity type.
    :type type: str
    :param identity_ids: The list of identities.
    :type identity_ids: list[str]
    """

    _validation = {
        'type': {'required': True},
        'identity_ids': {'required': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'identity_ids': {'key': 'identityIds', 'type': '[str]'},
    }

    def __init__(self, type, identity_ids):
        super(Identity, self).__init__()
        self.type = type
        self.identity_ids = identity_ids
