# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class OperationDetail(Model):
    """The detail about an operation.

    :param provider: The name of the provider that supports the operation.
    :type provider: str
    :param resource: The resource type on which this operation can be
     performed.
    :type resource: str
    :param operation: The name of the operation.
    :type operation: str
    :param description: The description of the operation.
    :type description: str
    """

    _attribute_map = {
        'provider': {'key': 'provider', 'type': 'str'},
        'resource': {'key': 'resource', 'type': 'str'},
        'operation': {'key': 'operation', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
    }

    def __init__(self, provider=None, resource=None, operation=None, description=None):
        super(OperationDetail, self).__init__()
        self.provider = provider
        self.resource = resource
        self.operation = operation
        self.description = description
