# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .service_unit_properties import ServiceUnitProperties


class ServiceUnit(ServiceUnitProperties):
    """Defines a service unit.

    :param target_resource_group: The Azure Resource Group to which the
     resources in the service unit belong to or should be deployed to.
    :type target_resource_group: str
    :param deployment_mode: Describes the type of ARM deployment to be
     performed on the resource. Possible values include: 'Incremental',
     'Complete'
    :type deployment_mode: str or ~deploymentmanager.models.DeploymentMode
    :param artifacts: The artifacts for the service unit.
    :type artifacts: ~deploymentmanager.models.ServiceUnitArtifacts
    :param name: Name of the service unit.
    :type name: str
    :param steps: Detailed step information, if present.
    :type steps: list[~deploymentmanager.models.RolloutStep]
    """

    _validation = {
        'target_resource_group': {'required': True},
        'deployment_mode': {'required': True},
    }

    _attribute_map = {
        'target_resource_group': {'key': 'targetResourceGroup', 'type': 'str'},
        'deployment_mode': {'key': 'deploymentMode', 'type': 'DeploymentMode'},
        'artifacts': {'key': 'artifacts', 'type': 'ServiceUnitArtifacts'},
        'name': {'key': 'name', 'type': 'str'},
        'steps': {'key': 'steps', 'type': '[RolloutStep]'},
    }

    def __init__(self, target_resource_group, deployment_mode, artifacts=None, name=None, steps=None):
        super(ServiceUnit, self).__init__(target_resource_group=target_resource_group, deployment_mode=deployment_mode, artifacts=artifacts)
        self.name = name
        self.steps = steps
