# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .step_properties import StepProperties


class WaitStepProperties(StepProperties):
    """Defines the properties of a Wait step.

    :param step_type: Constant filled by server.
    :type step_type: str
    :param attributes: The Wait attributes
    :type attributes: ~deploymentmanager.models.WaitStepAttributes
    """

    _validation = {
        'step_type': {'required': True},
    }

    _attribute_map = {
        'step_type': {'key': 'stepType', 'type': 'str'},
        'attributes': {'key': 'attributes', 'type': 'WaitStepAttributes'},
    }

    def __init__(self, attributes=None):
        super(WaitStepProperties, self).__init__()
        self.attributes = attributes
        self.step_type = 'Wait'
