[packaging]
package_name = "azure-mgmt-deploymentmanager"
package_nspkg = "azure-mgmt-nspkg"
package_pprint_name = "Deployment Manager Management"
package_doc_id = "deploymentmanager"
is_stable = true
is_arm = true
need_msrestazure = true
